[package]
name = "wfl"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = "0.15.0"
rand = "0.9.1"
regex = "1.10.3"
log = "0.4.20"
tokio = { version = "1.35.1", features = ["full"] }
reqwest = { version = "0.11.24", features = ["json"] }
sqlx = { version = "0.8.1", features = ["runtime-tokio-rustls", "sqlite", "mysql", "postgres"] }
serde_json = "1.0.114"

[dev-dependencies]
tempfile = "3.19.1"
